version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: wa-backend
    restart: unless-stopped
    # Coolify üzerinden domain atayacağımız için portu siliyoruz
    # (Coolify proxy'si kendi iç ağından 8000'e otomatik yönelecek)
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: 
      context: ./frontend
    container_name: wa-frontend
    restart: unless-stopped
    ports:
      # Siteniz 80 portundan veya Coolify hangi porta yönlendiriyorsa oradan yayınlanacak
      - "80:80"
    depends_on:
      - backend
